### ISSUE TITLE
能在哪些浏览器上正常运行？

### ISSUE THREAD

**Issue by lfire** [ecomfe/rider#26]
简单描述一下对各浏览器的支持程度

**Comment by firede** [comment]
通常意义上的 **浏览器兼容性** 是由 `Autoprefixer` 的配置决定的，将这些交给后处理器做更专业。
- 作为 Stylus 插件使用时：参考 [demo.js](https://github.com/ecomfe/rider/blob/master/demo.js#L30)
- 用 edp 作为构建工具时：参考 [配置说明](https://github.com/ecomfe/edp-provider-rider#可定制的选项)

一些特殊情况，比如 [多行文本截断，显示省略号](https://github.com/ecomfe/rider/blob/master/doc/typography.md#ellipsisline)，支持情况在文当中会有说明。

根据我们的实践情况看，Android 2.3+, iOS 6+ 以及 Chrome, Safari 等现代浏览器环境是可以放心用的。
